Repository STACK-UP-3/warriors-frontend, pull requests merged in 2020-05, with the labels that each got.

#2 Setup react from scratch
  .babelrc
  .env.example
  .eslintrc.json
  .gitignore
  .hound.yml
  README.md
  package-lock.json
  package.json
  public/index.html
  public/materialize.css
  public/materialize.min.css
  src/App.js
  src/app.scss
  src/components/Home.js
  src/index.js
  webpack.config.js
Labels: TTL REVIEW

#3 #171784029 Setup Travis CI to run tests
  .travis.yml
  README.md
  jest.config.json
  package-lock.json
  package.json
  src/index.js
  src/tests/enzyme.config.js
  src/tests/example.spec.js
  src/tests/example.test.js
Labels: Ready For Review, TTL Review

#5 #172933075 add fixing heroku link
  package-lock.json
  package.json
  public/index.html
  server/server.js
  webpack.config.js
Labels: TTL Review
